### PR TITLE
Add TypeChat service

### PR DESCRIPTION
**Pull request by abichinger**
Servus!

Thanks for this awesome tool!

I added a new services which uses OpenAI and TypeChat to translate all strings.

New services:
- `typechat` -  translates a batch of 10 with a single prompt
- `typechat-manual` - feed the prompt into a LLM and copy the result  

Environment variables:
| Name | Default |
|--------|--------|
| OPENAI_API_KEY | required |
| OPENAI_MODEL | `text-davinci-003` |
| OPENAI_ENDPOINT | `https://api.openai.com/v1/chat/completions` |
| OPEN_AI_BATCH_SIZE | `10` |
| TYPECHAT_SCHEMA_NAME | `AppLocalizations` | 
| TYPECHAT_SCHEMA_COMMENT | `undefined` | 

I wasn't able to test it with the official OpenAI API, because I don't have an OpenAI API key. But it worked with a local [llama-cpp-python](https://github.com/abetlen/llama-cpp-python#web-server) web server.

### Example

A generated prompt will look like this:
```
You are a service that translates user requests into JSON objects of type "AppLocalizations" according to the following TypeScript definitions:
\`\`\`
export interface AppLocalizations {
  globalRankings: string;
  share: string;
  shareText: string;
  rank: string;
  train: string;
  forfeit: string;
  forfeitContent: string;
  yes: string;
  no: string;
}
\`\`\`
The following is a user request:
"""
Translate the following JSON object from English into German:
{
  "globalRankings": "Global Rankings",
  "share": "Share",
  "shareText": "Yo! Check out Nono Battle.",
  "rank": "Rank",
  "train": "Practice",
  "forfeit": "Forfeit",
  "forfeitContent": "Are you sure you want to forfeit?",
  "yes": "Yes",
  "no": "No"
}
"""
The following is the user request translated into a JSON object with 2 spaces of indentation and no properties with the value undefined:

```

Response from ChatGPT:
```
Of course, here's the translated JSON object in German according to the provided TypeScript definitions:

\`\`\`json
{
  "globalRankings": "Weltweite Rangliste",
  "share": "Teilen",
  "shareText": "Hey! Schau dir Nono Battle an.",
  "rank": "Rang",
  "train": "Üben",
  "forfeit": "Aufgeben",
  "forfeitContent": "Bist du sicher, dass du aufgeben möchtest?",
  "yes": "Ja",
  "no": "Nein"
}
\`\`\`

The JSON object is formatted with 2 spaces of indentation, and properties with the value undefined have been omitted. If you need any further assistance or modifications, feel free to let me know!
```

### CODE REVIEW

**Comment by fkirc** [comment]
Thank you for submitting the PR!
The typechat-approach looks interesting and could be an alternative to the current openai-service with a primitive prompt-engineering.

However, there is currently the problem that the typechat-tests are failing in the CI: https://github.com/fkirc/attranslate/actions/runs/5770043007/job/15643564890?pr=256
image

Based on the test-summary, it seems that some module-import within the typechat-package is failing?

**Comment by abichinger** [comment]
Looks like typechat requires node >= 18. ([package.json](https://github.com/microsoft/TypeChat/blob/e8395ef2e4688ec7b94a7612046aeaec0af93046/package.json#L30C18-L30C18))

I added a check to ensure the correct node version is installed.

**Comment by fkirc** [comment]
After upgrading node to v18, I see a new CI-error:


src/util/util.ts:10:20 - error TS7016: Could not find a declaration file for module 'semver'. '/home/runner/work/attranslate/attranslate/node_modules/semver/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/semver` if it exists or add a new declaration (.d.ts) file containing `declare module 'semver';`

10 import semver from "semver";
                      ~~~~~~~~


Found 1 error.

**Comment by abichinger** [comment]
Oops, I forgot to commit `package.json`

**Comment by fkirc** [comment]
Now the CI passes again, I merged typechat and released version 2.1.0!
